const Categories = [
  "Fruits",
  "Vegetables",
  "Meat",
  "Dairy",
  "Bakery",
  "Beverages",
  "Seafood",
  "Grocery",
  "Nuts",
  "Snacks",
];

const Products = [
  {
    id: 0,
    name: "Apple",
    category: "Fruits",
    purchase_price: 100,
    sale_price: 120,
    govt_sale_price: null,
    tags: ["fresh", "fruit", "apple", "red"],
    date_added: "2023-03-15",
    date_updated: "2023-05-20",
  },
  {
    id: 1,
    name: "Banana",
    category: "Fruits",
    purchase_price: 50,
    sale_price: 60,
    govt_sale_price: 55,
    tags: ["fresh", "fruit", "banana", "yellow"],
    date_added: "2023-01-10",
    date_updated: "2023-04-05",
  },
  {
    id: 2,
    name: "Tomato",
    category: "Vegetables",
    purchase_price: 30,
    sale_price: 40,
    govt_sale_price: null,
    tags: ["fresh", "vegetable", "tomato", "red"],
    date_added: "2023-02-12",
    date_updated: "2023-06-18",
  },
  {
    id: 3,
    name: "Potato",
    category: "Vegetables",
    purchase_price: 25,
    sale_price: 35,
    govt_sale_price: null,
    tags: ["fresh", "vegetable", "potato", "root"],
    date_added: "2023-04-22",
    date_updated: "2023-07-30",
  },
  {
    id: 4,
    name: "Chicken",
    category: "Meat",
    purchase_price: 300,
    sale_price: 350,
    govt_sale_price: 320,
    tags: ["meat", "chicken", "protein", "fresh"],
    date_added: "2023-03-05",
    date_updated: "2023-06-10",
  },
  {
    id: 5,
    name: "Milk",
    category: "Dairy",
    purchase_price: 40,
    sale_price: 50,
    govt_sale_price: null,
    tags: ["dairy", "milk", "fresh", "calcium"],
    date_added: "2023-02-18",
    date_updated: "2023-05-25",
  },
  {
    id: 6,
    name: "Eggs",
    category: "Dairy",
    purchase_price: 80,
    sale_price: 90,
    govt_sale_price: 85,
    tags: ["dairy", "eggs", "protein", "fresh"],
    date_added: "2023-03-10",
    date_updated: "2023-07-15",
  },
  {
    id: 7,
    name: "Bread",
    category: "Bakery",
    purchase_price: 30,
    sale_price: 40,
    govt_sale_price: 35,
    tags: ["bakery", "bread", "wheat", "fresh"],
    date_added: "2023-04-01",
    date_updated: "2023-06-28",
  },
  {
    id: 8,
    name: "Butter",
    category: "Dairy",
    purchase_price: 120,
    sale_price: 140,
    govt_sale_price: null,
    tags: ["dairy", "butter", "fat", "spread"],
    date_added: "2023-01-25",
    date_updated: "2023-04-30",
  },
  {
    id: 9,
    name: "Cheddar Cheese",
    category: "Dairy",
    purchase_price: 200,
    sale_price: 220,
    govt_sale_price: 210,
    tags: ["dairy", "cheese", "cheddar", "yellow"],
    date_added: "2023-05-10",
    date_updated: "2023-07-20",
  },
  {
    id: 10,
    name: "Orange Juice",
    category: "Beverages",
    purchase_price: 150,
    sale_price: 170,
    govt_sale_price: null,
    tags: ["beverages", "juice", "orange", "drink"],
    date_added: "2023-02-05",
    date_updated: "2023-04-22",
  },
  {
    id: 11,
    name: "Broccoli",
    category: "Vegetables",
    purchase_price: 80,
    sale_price: 100,
    govt_sale_price: 90,
    tags: ["vegetables", "broccoli", "green", "fresh"],
    date_added: "2023-03-30",
    date_updated: "2023-06-15",
  },
  {
    id: 12,
    name: "Carrot",
    category: "Vegetables",
    purchase_price: 40,
    sale_price: 50,
    govt_sale_price: 45,
    tags: ["vegetables", "carrot", "orange", "root"],
    date_added: "2023-04-10",
    date_updated: "2023-07-01",
  },
  {
    id: 13,
    name: "Yogurt",
    category: "Dairy",
    purchase_price: 60,
    sale_price: 70,
    govt_sale_price: null,
    tags: ["dairy", "yogurt", "probiotic", "fresh"],
    date_added: "2023-01-12",
    date_updated: "2023-03-25",
  },
  {
    id: 14,
    name: "Beef Steak",
    category: "Meat",
    purchase_price: 400,
    sale_price: 450,
    govt_sale_price: null,
    tags: ["meat", "beef", "protein", "fresh"],
    date_added: "2023-02-22",
    date_updated: "2023-05-18",
  },
  {
    id: 15,
    name: "Salmon Fillet",
    category: "Seafood",
    purchase_price: 500,
    sale_price: 550,
    govt_sale_price: 530,
    tags: ["seafood", "salmon", "fish", "protein"],
    date_added: "2023-03-08",
    date_updated: "2023-06-01",
  },
  {
    id: 16,
    name: "Pasta",
    category: "Grocery",
    purchase_price: 70,
    sale_price: 90,
    govt_sale_price: null,
    tags: ["grocery", "pasta", "carbohydrate", "wheat"],
    date_added: "2023-04-25",
    date_updated: "2023-07-10",
  },
  {
    id: 17,
    name: "Rice",
    category: "Grocery",
    purchase_price: 80,
    sale_price: 100,
    govt_sale_price: 90,
    tags: ["grocery", "rice", "carbohydrate", "grain"],
    date_added: "2023-01-15",
    date_updated: "2023-04-20",
  },
  {
    id: 18,
    name: "Olive Oil",
    category: "Grocery",
    purchase_price: 300,
    sale_price: 320,
    govt_sale_price: null,
    tags: ["grocery", "oil", "olive", "healthy"],
    date_added: "2023-02-28",
    date_updated: "2023-05-12",
  },
  {
    id: 19,
    name: "Spinach",
    category: "Vegetables",
    purchase_price: 50,
    sale_price: 60,
    govt_sale_price: null,
    tags: ["vegetables", "spinach", "green", "leafy"],
    date_added: "2023-04-18",
    date_updated: "2023-06-27",
  },
  {
    id: 20,
    name: "Peanut Butter",
    category: "Grocery",
    purchase_price: 200,
    sale_price: 220,
    govt_sale_price: null,
    tags: ["grocery", "peanut", "butter", "spread"],
    date_added: "2023-01-18",
    date_updated: "2023-04-05",
  },
  {
    id: 21,
    name: "Almonds",
    category: "Nuts",
    purchase_price: 600,
    sale_price: 650,
    govt_sale_price: null,
    tags: ["nuts", "almonds", "healthy", "snack"],
    date_added: "2023-03-12",
    date_updated: "2023-06-08",
  },
  {
    id: 22,
    name: "Cereal",
    category: "Grocery",
    purchase_price: 120,
    sale_price: 140,
    govt_sale_price: 130,
    tags: ["grocery", "cereal", "breakfast", "grain"],
    date_added: "2023-02-02",
    date_updated: "2023-05-22",
  },
  {
    id: 23,
    name: "Chocolate Bar",
    category: "Snacks",
    purchase_price: 50,
    sale_price: 60,
    govt_sale_price: 55,
    tags: ["snacks", "chocolate", "sweet", "candy"],
    date_added: "2023-04-20",
    date_updated: "2023-06-30",
  },
];

export { Categories, Products };
