const products = [
  {
    id: 0,
    name: "Apple",
    category: "Fruits",
    purchase_price: 100,
    sale_price: 120,
    govt_sale_price: null,
    tags: ["fresh", "fruit", "apple", "red"],
  },
  {
    id: 1,
    name: "Banana",
    category: "Fruits",
    purchase_price: 50,
    sale_price: 60,
    govt_sale_price: 55,
    tags: ["fresh", "fruit", "banana", "yellow"],
  },
  {
    id: 2,
    name: "Tomato",
    category: "Vegetables",
    purchase_price: 30,
    sale_price: 40,
    govt_sale_price: null,
    tags: ["fresh", "vegetable", "tomato", "red"],
  },
  {
    id: 3,
    name: "Potato",
    category: "Vegetables",
    purchase_price: 25,
    sale_price: 35,
    govt_sale_price: null,
    tags: ["fresh", "vegetable", "potato", "root"],
  },
  {
    id: 4,
    name: "Chicken",
    category: "Meat",
    purchase_price: 300,
    sale_price: 350,
    govt_sale_price: 320,
    tags: ["meat", "chicken", "protein", "fresh"],
  },
  {
    id: 5,
    name: "Milk",
    category: "Dairy",
    purchase_price: 40,
    sale_price: 50,
    govt_sale_price: null,
    tags: ["dairy", "milk", "fresh", "calcium"],
  },
  {
    id: 6,
    name: "Eggs",
    category: "Dairy",
    purchase_price: 80,
    sale_price: 90,
    govt_sale_price: 85,
    tags: ["dairy", "eggs", "protein", "fresh"],
  },
  {
    id: 7,
    name: "Bread",
    category: "Bakery",
    purchase_price: 30,
    sale_price: 40,
    govt_sale_price: 35,
    tags: ["bakery", "bread", "wheat", "fresh"],
  },
  {
    id: 8,
    name: "Butter",
    category: "Dairy",
    purchase_price: 120,
    sale_price: 140,
    govt_sale_price: null,
    tags: ["dairy", "butter", "fat", "spread"],
  },
  {
    id: 9,
    name: "Cheddar Cheese",
    category: "Dairy",
    purchase_price: 200,
    sale_price: 220,
    govt_sale_price: 210,
    tags: ["dairy", "cheese", "cheddar", "yellow"],
  },
  {
    id: 10,
    name: "Orange Juice",
    category: "Beverages",
    purchase_price: 150,
    sale_price: 170,
    govt_sale_price: null,
    tags: ["beverages", "juice", "orange", "drink"],
  },
  {
    id: 11,
    name: "Broccoli",
    category: "Vegetables",
    purchase_price: 80,
    sale_price: 100,
    govt_sale_price: 90,
    tags: ["vegetables", "broccoli", "green", "fresh"],
  },
  {
    id: 12,
    name: "Carrot",
    category: "Vegetables",
    purchase_price: 40,
    sale_price: 50,
    govt_sale_price: 45,
    tags: ["vegetables", "carrot", "orange", "root"],
  },
  {
    id: 13,
    name: "Yogurt",
    category: "Dairy",
    purchase_price: 60,
    sale_price: 70,
    govt_sale_price: null,
    tags: ["dairy", "yogurt", "probiotic", "fresh"],
  },
  {
    id: 14,
    name: "Beef Steak",
    category: "Meat",
    purchase_price: 400,
    sale_price: 450,
    govt_sale_price: null,
    tags: ["meat", "beef", "protein", "fresh"],
  },
  {
    id: 15,
    name: "Salmon Fillet",
    category: "Seafood",
    purchase_price: 500,
    sale_price: 550,
    govt_sale_price: 530,
    tags: ["seafood", "salmon", "fish", "protein"],
  },
  {
    id: 16,
    name: "Pasta",
    category: "Grocery",
    purchase_price: 70,
    sale_price: 90,
    govt_sale_price: null,
    tags: ["grocery", "pasta", "carbohydrate", "wheat"],
  },
  {
    id: 17,
    name: "Rice",
    category: "Grocery",
    purchase_price: 80,
    sale_price: 100,
    govt_sale_price: 90,
    tags: ["grocery", "rice", "carbohydrate", "grain"],
  },
  {
    id: 18,
    name: "Olive Oil",
    category: "Grocery",
    purchase_price: 300,
    sale_price: 320,
    govt_sale_price: null,
    tags: ["grocery", "oil", "olive", "healthy"],
  },
  {
    id: 19,
    name: "Spinach",
    category: "Vegetables",
    purchase_price: 50,
    sale_price: 60,
    govt_sale_price: null,
    tags: ["vegetables", "spinach", "green", "leafy"],
  },
  {
    id: 20,
    name: "Peanut Butter",
    category: "Grocery",
    purchase_price: 200,
    sale_price: 220,
    govt_sale_price: null,
    tags: ["grocery", "peanut", "butter", "spread"],
  },
  {
    id: 21,
    name: "Almonds",
    category: "Nuts",
    purchase_price: 600,
    sale_price: 650,
    govt_sale_price: null,
    tags: ["nuts", "almonds", "healthy", "snack"],
  },
  {
    id: 22,
    name: "Cereal",
    category: "Grocery",
    purchase_price: 120,
    sale_price: 140,
    govt_sale_price: 130,
    tags: ["grocery", "cereal", "breakfast", "grain"],
  },
  {
    id: 23,
    name: "Chocolate Bar",
    category: "Snacks",
    purchase_price: 50,
    sale_price: 60,
    govt_sale_price: 55,
    tags: ["snacks", "chocolate", "sweet", "candy"],
  },
];

export default products;
